\c cta_dev;

INSERT INTO soaps (name, smell, ingredients, description, type, price, adult, baby, featured, rating, image) VALUES
('Natural', 'unscented', 'palm and coconut oil', 'color-free and fragrance-free and is air-dried wire-cut and aged to create a mild long-lasting soap bar', 'glycerin','$4.40', TRUE, TRUE, TRUE,'5','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXWOoAjNgpM7PIDZENqm1qeauE07RSWC_BQQ&usqp=CAU'),
('Pure', 'unscented', 'coconut oil castor oil, shea butter, jojoba oil, and other natural ingredients',' Ideal for those with sensitive skin and fragrance allergies ', 'glycerin','$7.40', TRUE, FALSE,FALSE,'4','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjR5fEmkHOpb_vY3ptMketQiUyGdygqTAIia5Ii4N19eCZ-HV1a6t1XYvUZXQy86YJClI&usqp=CAU'),
('Citrus & Sea Salt Body Wash', 'Citrus and Sea Salt', 'Coco Glycinate, essential oils, and Himalayan Sea Salt ',' Especially helpful for dry skin, this men & women body wash with the power to gently exfoliate, purify, and moisturize your skin. All while leaving it smelling fresh and fragrant ', 'gel','$20.99', TRUE, FALSE,TRUE,'4','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIaGJ7T6mP3Q-dDtI2JhMvj3qPSe4ZCsKzCw&usqp=CAU'),
('Organic Baby Wash', 'Vanilla Bean', 'Distilled Water, Castile Soap, Vanilla Bean Essential Oil, Oat Extract', 'Help calm baby before bedtime and features natural oat extract, specially formulated for infants, tear free','liquid', '$12.75',FALSE, TRUE, TRUE, '5','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2fkZcnm7eUiUx_a9Z5MUp9zI88Qpwrfy8Mw&usqp=CAU
'),
('African Black Soap', 'unsented', 'Sodium Palm Kernelate, Water, Glycerin, Fragrance (Parfum), Palmitic Acid, Butyrospermum Parkii (shea Butter)*, Helianthus Annuus, (Sunflower) Seed Oil (and) Salix Alba (Willow) Bark Extracts, Saponified Butyrospermum Parkii (Shea Butter), Saponified Cocos Nucifera (Coconut) Oil, Saponified Elaeis Guineensis (Palm) Kernel Oil, Cocoa Pod Ash, Avena Sativa (Oat) Kernel Meal, Carbon, Avena Sativa (oat) Kernel Flour, Melaleuca Alternifolia (Tea Tree) Leaf Oil, Sodium Chloride, Tetrasodium Edta, Tatresodium Etidronate', 'Cleanse, moisturize and comfort irritated skin','beauty/medicated', '$5.99', TRUE, TRUE, FALSE,'4','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXdlQSKEoZvbiVzX09LXTET8GDFb-QPtl2Ug&usqp=CAU'),
('Antifungal','palm','sodium palmate, sodium palm kernelate, water, glycderin','Treats fungal tinea pedis(athletes foot),tinea corporis, and tineas cruis', 'medicated', '$14.99',TRUE,FALSE,FALSE,'5','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzQZHdH3puBB69Td3t3E1AJALolvrW7mtSlw&usqp=CAU');


SELECT name FROM soaps;
